### ISSUE TITLE
Using certificates which contains "Apple Development" text causes DeviceAgent-Runner installation to fail

### ISSUE THREAD

**Issue by papalma** [calabash/iOSDeviceManager#262]
I've updated run_loop to 4.5.0 and found when using certificates with text "Apple Development:" iOSDeviceManager is unable to install DeviceAgent-Runner.app and crashes.

```
Calabash says, "Your wish is my command."
calabash-ios 0.21.10> start_test_server_in_background
SHELL: xcrun simctl list devices --json
SHELL: xcrun instruments -s devices
DEBUG: HTTP: get http://192.168.102.201:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: HTTP: get http://192.168.102.201:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
SHELL: cd /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop/device_agent
SHELL: ditto -xk Frameworks.zip .
SHELL: ditto -xk DeviceAgent-Runner.app.zip .
SHELL: /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop/device_agent/bin/iOSDeviceManager install /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id #dev_id#
Traceback (most recent call last):
       15: from /Users/ppalma/.rbenv/versions/2.6.3/bin/irb:23:in `<main>'
       14: from /Users/ppalma/.rbenv/versions/2.6.3/bin/irb:23:in `load'
       13: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       12: from (irb):1
       11: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/calabash-cucumber-0.21.10/lib/calabash-cucumber/core.rb:1576:in `start_test_server_in_background'
       10: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/calabash-cucumber-0.21.10/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
        9: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/calabash-cucumber-0.21.10/lib/calabash-cucumber/launcher.rb:412:in `new_run_loop'
        8: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/calabash-cucumber-0.21.10/lib/calabash-cucumber/launcher.rb:412:in `times'
        7: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/calabash-cucumber-0.21.10/lib/calabash-cucumber/launcher.rb:414:in `block in new_run_loop'
        6: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop.rb:113:in `run'
        5: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop/device_agent/client.rb:191:in `run'
        4: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop/device_agent/client.rb:325:in `launch'
        3: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop/device_agent/client.rb:1489:in `launch_cbx_runner'
        2: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop/device_agent/ios_device_manager.rb:146:in `launch'
        1: from /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop/shell.rb:116:in `run_shell_command'
RunLoop::Shell::Error ()
There was an error executing:

/Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop/device_agent/bin/iOSDeviceManager install /Users/ppalma/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/run_loop-4.5.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id #dev_id#

The command generated this output:

Application sh.calaba.DeviceAgent.xctrunner is not installed on #dev_id#
No valid iOSDeveloperIdentities found on system.
2019-11-22 11:15:50.052 iOSDeviceManager[44270:633764] *** Terminating app due to uncaught exception 'CBXException', reason: 'Unable to find appropriate codesign identity for device #dev_id# / app sh.calaba.DeviceAgent.xctrunner combo'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff43100acd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6d802a17 objc_exception_throw + 48
	2   iOSDeviceManager                    0x00000001084b0698 +[Command resourcesFromArgs:] + 0
	3   iOSDeviceManager                    0x00000001084baa80 +[MobileProfile bestMatchProfileForApplication:device:] + 284
	4   iOSDeviceManager                    0x00000001084a4e48 -[PhysicalDevice installApp:mobileProfile:codesignIdentity:resourcesToInject:forceReinstall:] + 430
	5   iOSDeviceManager                    0x00000001084a52e5 -[PhysicalDevice installApp:resourcesToInject:forceReinstall:] + 67
	6   iOSDeviceManager                    0x00000001084a817b +[InstallAppCommand execute:] + 876
	7   iOSDeviceManager                    0x00000001084b35b7 +[CLI process:] + 1110
	8   iOSDeviceManager                    0x000000010849ed25 main + 121
	9   libdyld.dylib                       0x00007fff6efd13d5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
calabash-ios 0.21.10>
```
Installing my old certificate which contains string "iPhone Developer:" fixed this issue installing DeviceAgent-Runner and avoid crashing.

As a workaround, allowing to use new certificates,  I've modified isIOSDeveloperIdentity() in iOSDeviceManager/Resigning/CodesignIdentity.m. to:
```
- (BOOL)isIOSDeveloperIdentity {
    return [self.name containsString:@"iPhone Developer"] || [self.name containsString:@"Apple Development"];
}
```

**Comment by jmoody** [comment]
Please make a pull request.

**Comment by akoeplinger** [comment]
PR was merged at https://github.com/calabash/iOSDeviceManager/pull/263.

**Comment by jmoody** [comment]
This is now available in Xamarin.UITest and run-loop.
